### ISSUE TITLE
Встает скрипт запуска игры ProjectCars2 попадая на нестандартный экран Параметры соперников 

### ISSUE THREAD

**Issue by Zulllus** [Tymonrare/gaming-center#20]
Происходит остановка запуска игры ProjectCars2. Выражается тем, что прокликиватель неправильно нажимает комбинацию или где-то не хватает тайминга. В итоге игра не стартует и попадает на экран Параметры соперников. 
![image](https://user-images.githubusercontent.com/12176258/43023142-716f093c-8c72-11e8-8e82-4ace3ee440c2.png)

**Comment by Tymonrare** [comment]
больший тайминг вроде помог
