### ISSUE TITLE
Проблемы со стимом

### ISSUE THREAD

**Issue by Zulllus** [Tymonrare/gaming-center#21]
Из-за различных событий стима происходит прерывание запуска (предположительно, т.к. на работу скрипта пока ни разу не попало). Например, стим перед запуском возникает диалог проверки (подготовка к запуску). Чаще всего диалог закрывается сам, т.к. обновлений не требуется, но если требуется обновление, то стим обновляет игру и показывает диалог обновления (прогрессбар). В этот момент игра не стартует, а обновляется. Но хуже всего, диалог после загрузги обновления автоматически не закрывается, а требует нажатия кнопки Играть. 
![image](https://user-images.githubusercontent.com/12176258/43023846-e8d7cc32-8c74-11e8-8e63-7d56c7556d28.png)

**Comment by Tymonrare** [comment]
Это происходит только при частом перезапуске игры, в реальном использовании это исключено

**Comment by Zulllus** [comment]
Ну, я лично сегодня нажимал на играть, просто в этот момент я запускал не через веб, а мышкой
