### ISSUE TITLE
Поворот платформы после конвертера

### ISSUE THREAD

**Issue by Zulllus** [Tymonrare/gaming-center#31]
Конвертер движения платформы работает плохо.

**Comment by Tymonrare** [comment]
Конвертер работает отлично.

А вот каким образом углы в старом софте обрабатывались и воспроизводились надо выяснять экспериментальным сравнением

**Comment by Zulllus** [comment]
Последнее тестирование показало, что все в приделах нормы. Конечно, есть куда улучшать. Но пока наверное в таком виде баг можно закрывать.
