### ISSUE TITLE
Некоторые проблемы отображения при рендринге на Планшете страницы управления

### ISSUE THREAD

**Issue by Zulllus** [Tymonrare/gaming-center#37]
Нужно поправить несколько проблем:
1. Заменить дублирующее название, например на Многопользовательский режим управления
2. Подвинуть надпись вправо
3. Подвинуть надпись вниз
![image](https://user-images.githubusercontent.com/12176258/43765847-99854948-9a39-11e8-908f-02eb94a9cbf8.png)

**Comment by Tymonrare** [comment]
Не актуально
